server {
    listen 80;
    server_name utils.caustico.ru;
    return 301 https://utils.caustico.ru$request_uri;
}

server {
    listen 443 ssl;
    server_name utils.caustico.ru;

    ssl_certificate     /etc/ssl/utilities-payment/fullchain.pem;
    ssl_certificate_key /etc/ssl/utilities-payment/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /var/www/utilities-payment-frontend;
    index index.html;

    location ~ ^/(users|bills|admin|ping) {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
